<?php

namespace TBFBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Users_SkillsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersSkillsRepository extends EntityRepository
{
}
