<?php

namespace TBFBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersRepository extends EntityRepository
{
    //vincent
    
    public function getUsersByIds($name){
        try {
            $qb = $this->createQueryBuilder('n');
            return $qb      ->leftJoin('n.skills', 'skillid')
                            ->addSelect('skillid')
                            ->leftJoin('n.projects', 'projectid')
                            ->addSelect('projectid')
                            ->where($qb->expr()->like('n.firstname', ':name'))
                            ->setParameter('name', '%' . $name . '%')
                            ->getQuery()
                            ->getResult();
        } catch (\Doctrine\DBAL\DBALException $e) {
           // echo $e->getTraceAsString();
        }
    }
}
