<?php

namespace TBFBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersRepository extends EntityRepository
{
    
   public function getUsersByName($name){
       try {
           $qb = $this->createQueryBuilder('n');
           return $qb      ->leftJoin('n.projects', 'projectid')
                           ->addSelect('projectid')
                           //->where($qb->expr()->like('n.firstname', ':name'))
                           ->where('n.firstname LIKE :name OR n.lastname LIKE :name')
                           ->setParameter('name', '%' . $name . '%')
                           ->getQuery()
                           ->getResult();
       } catch (\Doctrine\DBAL\DBALException $e) {
           echo $e->getTraceAsString();
       }

   }
    public function getUsersById($id) {
        return $this->createQueryBuilder('u')
            ->where('u.id = :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->getSingleResult();
    }

    public function getUsers() {
        return $this->createQueryBuilder('u')
            ->getQuery()
            ->getResult();
    }
}
